// ============================================================================
// Database tên tiếng Việt phổ biến cho bé
// ============================================================================

export interface VietnameseName {
  name: string;
  gender: "male" | "female" | "unisex";
  meaning: string;
}

export const VIETNAMESE_NAMES: VietnameseName[] = [
  // === Nam ===
  { name: "An", gender: "male", meaning: "Bình an, yên ổn" },
  { name: "Anh", gender: "unisex", meaning: "Anh hùng, xuất sắc" },
  { name: "Bảo", gender: "unisex", meaning: "Quý báu, bảo vệ" },
  { name: "Bình", gender: "male", meaning: "Bình yên, hòa bình" },
  { name: "Cường", gender: "male", meaning: "Mạnh mẽ, cường tráng" },
  { name: "Dũng", gender: "male", meaning: "Dũng cảm, can đảm" },
  { name: "Đạt", gender: "male", meaning: "Đạt được, thành đạt" },
  { name: "Đức", gender: "male", meaning: "Đức hạnh, phẩm chất tốt" },
  { name: "Hải", gender: "male", meaning: "Biển cả, rộng lớn" },
  { name: "Hiếu", gender: "male", meaning: "Hiếu thảo, có hiếu" },
  { name: "Hoàng", gender: "male", meaning: "Hoàng đế, vàng, cao quý" },
  { name: "Hùng", gender: "male", meaning: "Anh hùng, mạnh mẽ" },
  { name: "Huy", gender: "male", meaning: "Huy hoàng, rực rỡ" },
  { name: "Khải", gender: "male", meaning: "Khai sáng, mở ra" },
  { name: "Khang", gender: "male", meaning: "Khang trang, khỏe mạnh" },
  { name: "Khánh", gender: "unisex", meaning: "Khánh hỉ, vui mừng" },
  { name: "Kiên", gender: "male", meaning: "Kiên cường, bền bỉ" },
  { name: "Lâm", gender: "male", meaning: "Rừng, thiên nhiên" },
  { name: "Long", gender: "male", meaning: "Rồng, thịnh vượng" },
  { name: "Minh", gender: "unisex", meaning: "Sáng suốt, thông minh" },
  { name: "Nam", gender: "male", meaning: "Phương nam, nam tính" },
  { name: "Nghĩa", gender: "male", meaning: "Nghĩa khí, chính nghĩa" },
  { name: "Nhân", gender: "male", meaning: "Nhân ái, con người" },
  { name: "Phát", gender: "male", meaning: "Phát triển, thịnh vượng" },
  { name: "Phong", gender: "male", meaning: "Phong cách, gió" },
  { name: "Phúc", gender: "male", meaning: "Phúc lành, may mắn" },
  { name: "Quân", gender: "male", meaning: "Quân tử, thanh lịch" },
  { name: "Quang", gender: "male", meaning: "Quang minh, sáng sủa" },
  { name: "Sơn", gender: "male", meaning: "Núi, vững chãi" },
  { name: "Tài", gender: "male", meaning: "Tài năng, giỏi giang" },
  { name: "Thành", gender: "male", meaning: "Thành công, thành đạt" },
  { name: "Thiện", gender: "male", meaning: "Thiện lành, tốt bụng" },
  { name: "Thịnh", gender: "male", meaning: "Thịnh vượng, phồn thịnh" },
  { name: "Trí", gender: "male", meaning: "Trí tuệ, thông minh" },
  { name: "Trung", gender: "male", meaning: "Trung thành, chính trực" },
  { name: "Tuấn", gender: "male", meaning: "Tuấn tú, tài giỏi" },
  { name: "Tùng", gender: "male", meaning: "Cây tùng, kiên cường" },
  { name: "Vĩ", gender: "male", meaning: "Vĩ đại, to lớn" },
  { name: "Vinh", gender: "male", meaning: "Vinh quang, vinh dự" },
  { name: "Vũ", gender: "male", meaning: "Vũ trụ, mưa" },
  { name: "Duy", gender: "male", meaning: "Duy nhất, đặc biệt" },
  { name: "Hưng", gender: "male", meaning: "Hưng thịnh, phát triển" },
  { name: "Khôi", gender: "male", meaning: "Khôi ngô, tuấn tú" },
  { name: "Lộc", gender: "male", meaning: "Phúc lộc, may mắn" },
  { name: "Quốc", gender: "male", meaning: "Quốc gia, đất nước" },
  { name: "Toàn", gender: "male", meaning: "Toàn vẹn, hoàn hảo" },
  { name: "Triết", gender: "male", meaning: "Triết lý, sâu sắc" },
  { name: "Thắng", gender: "male", meaning: "Chiến thắng, vượt trội" },
  { name: "Hào", gender: "male", meaning: "Hào hoa, phóng khoáng" },
  { name: "Đăng", gender: "male", meaning: "Đăng khoa, thành công" },
  { name: "Công", gender: "male", meaning: "Công minh, công bằng" },
  { name: "Khoa", gender: "male", meaning: "Khoa bảng, tài năng" },
  { name: "Đông", gender: "male", meaning: "Phương đông, mùa đông" },
  { name: "Tâm", gender: "unisex", meaning: "Tấm lòng, trái tim" },
  { name: "Hậu", gender: "male", meaning: "Hậu thuẫn, phúc hậu" },
  { name: "Hiệp", gender: "male", meaning: "Hiệp sĩ, nghĩa hiệp" },
  { name: "Hòa", gender: "unisex", meaning: "Hòa bình, hòa hợp" },
  { name: "Lợi", gender: "male", meaning: "Lợi ích, thuận lợi" },
  { name: "Luân", gender: "male", meaning: "Luân lý, đạo đức" },
  { name: "Mạnh", gender: "male", meaning: "Mạnh mẽ, cường tráng" },
  { name: "Phi", gender: "male", meaning: "Bay cao, phi thường" },
  { name: "Sang", gender: "male", meaning: "Sang trọng, cao quý" },
  { name: "Sĩ", gender: "male", meaning: "Sĩ phu, học thức" },
  { name: "Tấn", gender: "male", meaning: "Tấn tới, tiến bộ" },
  { name: "Thái", gender: "male", meaning: "Thái bình, vĩ đại" },
  { name: "Thuận", gender: "male", meaning: "Thuận lợi, hòa thuận" },
  { name: "Tiến", gender: "male", meaning: "Tiến bộ, tiến lên" },
  { name: "Tín", gender: "male", meaning: "Tín nghĩa, đáng tin" },
  { name: "Trường", gender: "male", meaning: "Trường tồn, lâu dài" },
  { name: "Tuyến", gender: "male", meaning: "Tuyến đường, lựa chọn" },
  { name: "Uy", gender: "male", meaning: "Uy nghiêm, oai phong" },
  { name: "Việt", gender: "male", meaning: "Việt Nam, vượt qua" },
  { name: "Vương", gender: "male", meaning: "Vương giả, cao quý" },
  { name: "Dương", gender: "male", meaning: "Mặt trời, dương khí" },
  { name: "Định", gender: "male", meaning: "Định hướng, ổn định" },
  { name: "Chí", gender: "male", meaning: "Chí khí, ý chí" },
  { name: "Châu", gender: "male", meaning: "Châu ngọc, quý giá" },
  { name: "Dân", gender: "male", meaning: "Nhân dân, dân chủ" },
  { name: "Giang", gender: "male", meaning: "Sông lớn, bao la" },
  { name: "Kỳ", gender: "male", meaning: "Kỳ diệu, phi thường" },
  { name: "Lực", gender: "male", meaning: "Sức lực, mạnh mẽ" },
  { name: "Ninh", gender: "male", meaning: "Yên bình, an ninh" },
  { name: "Quý", gender: "male", meaning: "Quý giá, quý phái" },
  { name: "Sáng", gender: "male", meaning: "Sáng suốt, rạng rỡ" },
  { name: "Tháp", gender: "male", meaning: "Vững chãi, cao lớn" },
  { name: "Thọ", gender: "male", meaning: "Trường thọ, sống lâu" },
  { name: "Trực", gender: "male", meaning: "Chính trực, ngay thẳng" },
  { name: "Tuân", gender: "male", meaning: "Tuân thủ, kỷ luật" },
  { name: "Bách", gender: "male", meaning: "Cây bách, trăm — bền bỉ" },
  { name: "Đại", gender: "male", meaning: "To lớn, vĩ đại" },
  { name: "Hữu", gender: "male", meaning: "Có, hữu ích" },
  { name: "Nhật", gender: "male", meaning: "Mặt trời, Nhật Bản" },
  { name: "Phước", gender: "male", meaning: "Phước lành, may mắn" },
  // === Nữ ===
  { name: "Anh", gender: "unisex", meaning: "Anh hùng, xuất sắc" },
  { name: "Chi", gender: "female", meaning: "Chi lan, thanh nhã" },
  { name: "Diệp", gender: "female", meaning: "Lá cây, tươi mát" },
  { name: "Dung", gender: "female", meaning: "Dung nhan, xinh đẹp" },
  { name: "Giang", gender: "female", meaning: "Sông, bao la" },
  { name: "Hà", gender: "female", meaning: "Sông Hà, dịu dàng" },
  { name: "Hạnh", gender: "female", meaning: "Hạnh phúc, may mắn" },
  { name: "Hiền", gender: "female", meaning: "Hiền lành, dịu dàng" },
  { name: "Hoa", gender: "female", meaning: "Bông hoa, xinh đẹp" },
  { name: "Hương", gender: "female", meaning: "Hương thơm, ngọt ngào" },
  { name: "Khanh", gender: "female", meaning: "Khanh tướng, cao quý" },
  { name: "Lan", gender: "female", meaning: "Hoa lan, thanh cao" },
  { name: "Linh", gender: "unisex", meaning: "Linh thiêng, thông minh" },
  { name: "Loan", gender: "female", meaning: "Chim loan, quý phái" },
  { name: "Mai", gender: "female", meaning: "Hoa mai, thanh nhã" },
  { name: "My", gender: "female", meaning: "Xinh đẹp, mỹ miều" },
  { name: "Ngân", gender: "female", meaning: "Ngân hà, bạc" },
  { name: "Ngọc", gender: "female", meaning: "Ngọc quý, quý giá" },
  { name: "Nhung", gender: "female", meaning: "Nhung nhớ, mềm mại" },
  { name: "Phương", gender: "female", meaning: "Phương hướng, hương thơm" },
  { name: "Quỳnh", gender: "female", meaning: "Hoa quỳnh, xinh đẹp" },
  { name: "Thanh", gender: "unisex", meaning: "Thanh cao, trong sạch" },
  { name: "Thảo", gender: "female", meaning: "Cỏ cây, hiền thảo" },
  { name: "Thu", gender: "female", meaning: "Mùa thu, dịu dàng" },
  { name: "Thủy", gender: "female", meaning: "Nước, trong trẻo" },
  { name: "Trang", gender: "female", meaning: "Trang nhã, đẹp đẽ" },
  { name: "Trinh", gender: "female", meaning: "Trinh nguyên, trong sạch" },
  { name: "Trúc", gender: "female", meaning: "Cây trúc, thanh cao" },
  { name: "Tuyết", gender: "female", meaning: "Tuyết trắng, trong trẻo" },
  { name: "Uyên", gender: "female", meaning: "Uyên bác, học thức" },
  { name: "Vân", gender: "female", meaning: "Mây, tự do" },
  { name: "Vy", gender: "female", meaning: "Nhỏ nhắn, quý phái" },
  { name: "Yến", gender: "female", meaning: "Chim yến, duyên dáng" },
  { name: "Châu", gender: "female", meaning: "Châu ngọc, quý giá" },
  { name: "Đào", gender: "female", meaning: "Hoa đào, xinh đẹp" },
  { name: "Hằng", gender: "female", meaning: "Trăng, vĩnh hằng" },
  { name: "Huệ", gender: "female", meaning: "Hoa huệ, tinh khiết" },
  { name: "Khuê", gender: "female", meaning: "Sao khuê, tài năng" },
  { name: "Liên", gender: "female", meaning: "Hoa sen, thanh khiết" },
  { name: "Nhi", gender: "female", meaning: "Nhỏ bé, đáng yêu" },
  { name: "Thư", gender: "female", meaning: "Thư thái, nhẹ nhàng" },
  { name: "Trâm", gender: "female", meaning: "Trâm anh, cao quý" },
  { name: "Ánh", gender: "female", meaning: "Ánh sáng, rực rỡ" },
  { name: "Băng", gender: "female", meaning: "Băng giá, trong sáng" },
  { name: "Cúc", gender: "female", meaning: "Hoa cúc, kiên nhẫn" },
  { name: "Dao", gender: "female", meaning: "Tiên nữ, xinh đẹp" },
  { name: "Huyền", gender: "female", meaning: "Huyền bí, sâu sắc" },
  { name: "Kim", gender: "female", meaning: "Vàng, quý giá" },
  { name: "Nguyệt", gender: "female", meaning: "Trăng, dịu dàng" },
  { name: "Xuân", gender: "unisex", meaning: "Mùa xuân, tươi mới" },
  { name: "Bích", gender: "female", meaning: "Ngọc bích, quý giá" },
  { name: "Cẩm", gender: "female", meaning: "Cẩm thạch, đẹp đẽ" },
  { name: "Diễm", gender: "female", meaning: "Diễm lệ, xinh đẹp" },
  { name: "Đan", gender: "female", meaning: "Đan xen, khéo léo" },
  { name: "Hoài", gender: "female", meaning: "Hoài niệm, nhớ nhung" },
  { name: "Hồng", gender: "female", meaning: "Màu hồng, tươi đẹp" },
  { name: "Lệ", gender: "female", meaning: "Lệ hoa, xinh đẹp" },
  { name: "Mỹ", gender: "female", meaning: "Xinh đẹp, mỹ miều" },
  { name: "Như", gender: "female", meaning: "Như ý, toại nguyện" },
  { name: "Oanh", gender: "female", meaning: "Chim oanh, duyên dáng" },
  { name: "Thúy", gender: "female", meaning: "Thúy ngọc, xanh biếc" },
  { name: "Thùy", gender: "female", meaning: "Thùy mị, dịu dàng" },
  { name: "Tiên", gender: "female", meaning: "Tiên nữ, xinh đẹp" },
  { name: "Trà", gender: "female", meaning: "Trà hương, thanh nhã" },
  { name: "Yên", gender: "female", meaning: "Yên bình, tĩnh lặng" },
  { name: "Nga", gender: "female", meaning: "Hằng Nga, xinh đẹp" },
  { name: "Út", gender: "female", meaning: "Bé út, nhỏ nhất" },
  { name: "Quyên", gender: "female", meaning: "Quyên góp, đẹp đẽ" },
  { name: "Tuyền", gender: "female", meaning: "Suối nguồn, trong trẻo" },
  { name: "Thương", gender: "female", meaning: "Yêu thương, trìu mến" },
  { name: "Kiều", gender: "female", meaning: "Kiều diễm, xinh đẹp" },
  { name: "Lý", gender: "female", meaning: "Lý trí, thông minh" },
  { name: "Phượng", gender: "female", meaning: "Chim phượng, cao quý" },
  { name: "Tình", gender: "female", meaning: "Tình cảm, yêu thương" },
  { name: "Xuyến", gender: "female", meaning: "Xuyến chi, nhỏ xinh" },
  { name: "Diệu", gender: "female", meaning: "Diệu kỳ, tuyệt vời" },
];

// Tên đệm phổ biến
export const MIDDLE_NAMES: { name: string; gender: "male" | "female" }[] = [
  // === Nam ===
  { name: "Văn", gender: "male" },
  { name: "Hữu", gender: "male" },
  { name: "Đức", gender: "male" },
  { name: "Công", gender: "male" },
  { name: "Quốc", gender: "male" },
  { name: "Minh", gender: "male" },
  { name: "Thanh", gender: "male" },
  { name: "Xuân", gender: "male" },
  { name: "Gia", gender: "male" },
  { name: "Anh", gender: "male" },
  { name: "Bảo", gender: "male" },
  { name: "Trọng", gender: "male" },
  { name: "Tiến", gender: "male" },
  { name: "Đình", gender: "male" },
  { name: "Nhật", gender: "male" },
  { name: "Trung", gender: "male" },
  { name: "Thành", gender: "male" },
  { name: "Đại", gender: "male" },
  { name: "Hoàng", gender: "male" },
  { name: "Phúc", gender: "male" },
  // === Nữ ===
  { name: "Thị", gender: "female" },
  { name: "Ngọc", gender: "female" },
  { name: "Phương", gender: "female" },
  { name: "Thuỳ", gender: "female" },
  { name: "Hoài", gender: "female" },
  { name: "Thanh", gender: "female" },
  { name: "Minh", gender: "female" },
  { name: "Xuân", gender: "female" },
  { name: "Bích", gender: "female" },
  { name: "Diệu", gender: "female" },
  { name: "Hồng", gender: "female" },
  { name: "Kim", gender: "female" },
  { name: "Mỹ", gender: "female" },
  { name: "Tường", gender: "female" },
  { name: "Yên", gender: "female" },
  { name: "Gia", gender: "female" },
  { name: "Hải", gender: "female" },
  { name: "Khánh", gender: "female" },
  { name: "Thiên", gender: "female" },
  { name: "Quỳnh", gender: "female" },
];

// Họ phổ biến ở Việt Nam
export const LAST_NAMES: string[] = [
  "Nguyễn", "Trần", "Lê", "Phạm", "Hoàng", "Huỳnh", "Phan", "Vũ",
  "Võ", "Đặng", "Bùi", "Đỗ", "Hồ", "Ngô", "Dương", "Lý",
  "Đào", "Đinh", "Lương", "Mai", "Trịnh", "Tô", "Cao", "Lâm",
];

// Biệt danh phổ biến cho bé
export interface Nickname {
  name: string;
  gender: "male" | "female" | "unisex";
  category: "cute" | "animal" | "fruit" | "nature" | "english" | "other";
  meaning: string;
}

export const NICKNAMES: Nickname[] = [
  // === Dễ thương ===
  { name: "Bông", gender: "unisex", category: "cute", meaning: "Bông hoa, mềm mại" },
  { name: "Bin", gender: "male", category: "cute", meaning: "Bé nhỏ, đáng yêu" },
  { name: "Bí", gender: "unisex", category: "cute", meaning: "Bí ẩn, dễ thương" },
  { name: "Bi", gender: "unisex", category: "cute", meaning: "Viên bi, tròn xinh" },
  { name: "Bo", gender: "male", category: "cute", meaning: "Bé Bo, vui vẻ" },
  { name: "Bún", gender: "female", category: "cute", meaning: "Mềm mại, trắng trẻo" },
  { name: "Búp", gender: "female", category: "cute", meaning: "Búp bê, xinh xắn" },
  { name: "Na", gender: "female", category: "cute", meaning: "Bé Na, ngọt ngào" },
  { name: "Nấm", gender: "female", category: "cute", meaning: "Nấm nhỏ, đáng yêu" },
  { name: "Su", gender: "female", category: "cute", meaning: "Bé Su, dịu dàng" },
  { name: "Sóc", gender: "unisex", category: "cute", meaning: "Nhanh nhẹn, hoạt bát" },
  { name: "Tí", gender: "unisex", category: "cute", meaning: "Bé tí, nhỏ nhắn" },
  { name: "Tép", gender: "female", category: "cute", meaning: "Tép nhỏ, xinh xắn" },
  { name: "Bầu", gender: "unisex", category: "cute", meaning: "Tròn tròn, dễ thương" },
  { name: "Cún", gender: "male", category: "cute", meaning: "Cún con, nghịch ngợm" },
  { name: "Mập", gender: "unisex", category: "cute", meaning: "Bụ bẫm, khỏe mạnh" },
  { name: "Sữa", gender: "unisex", category: "cute", meaning: "Trắng trẻo, ngọt ngào" },
  { name: "Nhím", gender: "unisex", category: "cute", meaning: "Nhỏ nhắn, đáng yêu" },
  { name: "Bơ", gender: "unisex", category: "cute", meaning: "Mịn màng, dễ thương" },
  { name: "Gạo", gender: "unisex", category: "cute", meaning: "Thuần khiết, giản dị" },

  // === Động vật ===
  { name: "Gấu", gender: "male", category: "animal", meaning: "Mạnh mẽ, ấm áp" },
  { name: "Mèo", gender: "female", category: "animal", meaning: "Khéo léo, duyên dáng" },
  { name: "Cáo", gender: "male", category: "animal", meaning: "Thông minh, nhanh nhẹn" },
  { name: "Thỏ", gender: "female", category: "animal", meaning: "Hiền lành, dễ thương" },
  { name: "Cọp", gender: "male", category: "animal", meaning: "Dũng mãnh, mạnh mẽ" },
  { name: "Ong", gender: "unisex", category: "animal", meaning: "Chăm chỉ, siêng năng" },
  { name: "Voi", gender: "male", category: "animal", meaning: "To lớn, hiền lành" },
  { name: "Kiến", gender: "unisex", category: "animal", meaning: "Kiên trì, đoàn kết" },
  { name: "Sáo", gender: "female", category: "animal", meaning: "Vui tươi, ca hát" },
  { name: "Rồng", gender: "male", category: "animal", meaning: "Quyền lực, cao quý" },

  // === Trái cây ===
  { name: "Táo", gender: "unisex", category: "fruit", meaning: "Tươi mát, khỏe mạnh" },
  { name: "Đào", gender: "female", category: "fruit", meaning: "Hồng hào, xinh đẹp" },
  { name: "Cam", gender: "unisex", category: "fruit", meaning: "Ngọt ngào, tươi sáng" },
  { name: "Xoài", gender: "unisex", category: "fruit", meaning: "Ngọt ngào, nhiệt đới" },
  { name: "Mít", gender: "male", category: "fruit", meaning: "Ngọt lịm, vui vẻ" },
  { name: "Dâu", gender: "female", category: "fruit", meaning: "Nhỏ xinh, ngọt ngào" },
  { name: "Cherry", gender: "female", category: "fruit", meaning: "Ngọt ngào, đáng yêu" },
  { name: "Nho", gender: "unisex", category: "fruit", meaning: "Nhỏ nhắn, quý giá" },
  { name: "Chanh", gender: "unisex", category: "fruit", meaning: "Tươi mát, sảng khoái" },
  { name: "Lựu", gender: "female", category: "fruit", meaning: "Đỏ thắm, may mắn" },

  // === Thiên nhiên ===
  { name: "Mây", gender: "female", category: "nature", meaning: "Nhẹ nhàng, tự do" },
  { name: "Sao", gender: "female", category: "nature", meaning: "Lấp lánh, rực rỡ" },
  { name: "Nắng", gender: "female", category: "nature", meaning: "Ấm áp, tươi sáng" },
  { name: "Gió", gender: "male", category: "nature", meaning: "Tự do, phóng khoáng" },
  { name: "Suối", gender: "female", category: "nature", meaning: "Trong trẻo, êm đềm" },
  { name: "Sương", gender: "female", category: "nature", meaning: "Mát lành, thanh khiết" },
  { name: "Lá", gender: "unisex", category: "nature", meaning: "Tươi xanh, sinh động" },
  { name: "Sen", gender: "female", category: "nature", meaning: "Thanh khiết, cao quý" },

  // === Tên tiếng Anh / quốc tế ===
  { name: "Lucky", gender: "unisex", category: "english", meaning: "May mắn" },
  { name: "Sunny", gender: "unisex", category: "english", meaning: "Rạng rỡ, vui vẻ" },
  { name: "Ben", gender: "male", category: "english", meaning: "Con trai, phước lành" },
  { name: "Tom", gender: "male", category: "english", meaning: "Cậu bé, giản dị" },
  { name: "Mia", gender: "female", category: "english", meaning: "Của tôi, yêu thương" },
  { name: "Lily", gender: "female", category: "english", meaning: "Hoa lily, tinh khiết" },
  { name: "Amy", gender: "female", category: "english", meaning: "Yêu dấu" },
  { name: "Sam", gender: "male", category: "english", meaning: "Được lắng nghe" },
  { name: "Max", gender: "male", category: "english", meaning: "Vĩ đại nhất" },
  { name: "Luna", gender: "female", category: "english", meaning: "Mặt trăng" },

  // === Trending 2026 — Năm Bính Ngọ (Ngựa Lửa) ===
  { name: "Ngựa", gender: "male", category: "animal", meaning: "Mạnh mẽ, tự do — con giáp 2026" },
  { name: "Pony", gender: "unisex", category: "english", meaning: "Ngựa nhỏ, năng động" },
  { name: "Lửa", gender: "male", category: "nature", meaning: "Nhiệt huyết, bùng cháy — Bính Ngọ" },
  { name: "Cỏ", gender: "unisex", category: "nature", meaning: "Giản dị, sức sống mãnh liệt" },
  { name: "Mây Bay", gender: "female", category: "nature", meaning: "Tự do, phiêu lưu" },
  { name: "Hổ Phách", gender: "unisex", category: "nature", meaning: "Ấm áp, quý giá — tông lửa" },

  // === Gen Alpha / TikTok trending ===
  { name: "Boba", gender: "unisex", category: "other", meaning: "Trà sữa, ngọt ngào trendy" },
  { name: "Latte", gender: "unisex", category: "other", meaning: "Mịn màng, thanh lịch" },
  { name: "Matcha", gender: "unisex", category: "other", meaning: "Tươi mát, healthy" },
  { name: "Oreo", gender: "unisex", category: "other", meaning: "Đen trắng, vui nhộn" },
  { name: "Donut", gender: "unisex", category: "other", meaning: "Tròn xinh, ngọt ngào" },
  { name: "Jellybean", gender: "unisex", category: "other", meaning: "Nhiều màu sắc, vui vẻ" },
  { name: "Cookie", gender: "unisex", category: "other", meaning: "Ngọt ngào, ai cũng yêu" },
  { name: "Marshmallow", gender: "unisex", category: "other", meaning: "Mềm mịn, trắng trẻo" },

  // === Tên Hàn / Nhật trending ===
  { name: "Yuki", gender: "female", category: "english", meaning: "Tuyết (Nhật), tinh khiết" },
  { name: "Haru", gender: "unisex", category: "english", meaning: "Mùa xuân (Nhật), tươi mới" },
  { name: "Momo", gender: "female", category: "english", meaning: "Đào (Nhật), xinh đẹp" },
  { name: "Sora", gender: "unisex", category: "english", meaning: "Bầu trời (Nhật), tự do" },
  { name: "Kimi", gender: "female", category: "english", meaning: "Người quý giá (Nhật)" },
  { name: "Ryu", gender: "male", category: "english", meaning: "Rồng (Nhật), mạnh mẽ" },
  { name: "Kai", gender: "male", category: "english", meaning: "Biển (Nhật/Hawaii), rộng lớn" },

  // === Dễ thương bổ sung ===
  { name: "Kẹo", gender: "female", category: "cute", meaning: "Ngọt ngào, rực rỡ" },
  { name: "Sún", gender: "unisex", category: "cute", meaning: "Bé sún, đáng yêu" },
  { name: "Tôm", gender: "male", category: "cute", meaning: "Bé Tôm, nghịch ngợm" },
  { name: "Cà", gender: "unisex", category: "cute", meaning: "Bé Cà, giản dị" },
  { name: "Mũm", gender: "unisex", category: "cute", meaning: "Mũm mĩm, bụ bẫm" },
  { name: "Bắp", gender: "male", category: "cute", meaning: "Bắp ngô, khỏe mạnh" },
  { name: "Đậu", gender: "unisex", category: "cute", meaning: "Đậu nhỏ, xinh xắn" },
  { name: "Mèo Con", gender: "female", category: "cute", meaning: "Nhỏ nhắn, duyên dáng" },
  { name: "Gấu Bông", gender: "unisex", category: "cute", meaning: "Ôm ấp, dễ thương" },

  // === Khác ===
  { name: "Ku", gender: "male", category: "other", meaning: "Bé trai, dễ thương" },
  { name: "Mimi", gender: "female", category: "other", meaning: "Nhỏ nhắn, xinh xắn" },
  { name: "Bon", gender: "male", category: "other", meaning: "Tốt lành, vui vẻ" },
  { name: "Tin", gender: "male", category: "other", meaning: "Niềm tin, hy vọng" },
  { name: "Min", gender: "unisex", category: "other", meaning: "Nhỏ bé, thông minh" },
  { name: "Kiwi", gender: "unisex", category: "other", meaning: "Độc đáo, tươi mới" },
  { name: "Mochi", gender: "unisex", category: "other", meaning: "Mềm mại, ngọt ngào" },
  { name: "Pudding", gender: "unisex", category: "other", meaning: "Ngọt ngào, mềm mịn" },
  { name: "Chip", gender: "male", category: "other", meaning: "Nhỏ gọn, nhanh nhẹn" },
  { name: "Nana", gender: "female", category: "other", meaning: "Duyên dáng, dễ thương" },
];
