// ============================================================================
// Database tên tiếng Việt phổ biến cho bé
// ============================================================================

export interface VietnameseName {
  name: string;
  gender: "male" | "female" | "unisex";
  meaning: string;
}

export const VIETNAMESE_NAMES: VietnameseName[] = [
  // === Nam ===
  { name: "An", gender: "male", meaning: "Bình an, yên ổn" },
  { name: "Anh", gender: "unisex", meaning: "Anh hùng, xuất sắc" },
  { name: "Bảo", gender: "unisex", meaning: "Quý báu, bảo vệ" },
  { name: "Bình", gender: "male", meaning: "Bình yên, hòa bình" },
  { name: "Cường", gender: "male", meaning: "Mạnh mẽ, cường tráng" },
  { name: "Dũng", gender: "male", meaning: "Dũng cảm, can đảm" },
  { name: "Đạt", gender: "male", meaning: "Đạt được, thành đạt" },
  { name: "Đức", gender: "male", meaning: "Đức hạnh, phẩm chất tốt" },
  { name: "Hải", gender: "male", meaning: "Biển cả, rộng lớn" },
  { name: "Hiếu", gender: "male", meaning: "Hiếu thảo, có hiếu" },
  { name: "Hoàng", gender: "male", meaning: "Hoàng đế, vàng, cao quý" },
  { name: "Hùng", gender: "male", meaning: "Anh hùng, mạnh mẽ" },
  { name: "Huy", gender: "male", meaning: "Huy hoàng, rực rỡ" },
  { name: "Khải", gender: "male", meaning: "Khai sáng, mở ra" },
  { name: "Khang", gender: "male", meaning: "Khang trang, khỏe mạnh" },
  { name: "Khánh", gender: "unisex", meaning: "Khánh hỉ, vui mừng" },
  { name: "Kiên", gender: "male", meaning: "Kiên cường, bền bỉ" },
  { name: "Lâm", gender: "male", meaning: "Rừng, thiên nhiên" },
  { name: "Long", gender: "male", meaning: "Rồng, thịnh vượng" },
  { name: "Minh", gender: "unisex", meaning: "Sáng suốt, thông minh" },
  { name: "Nam", gender: "male", meaning: "Phương nam, nam tính" },
  { name: "Nghĩa", gender: "male", meaning: "Nghĩa khí, chính nghĩa" },
  { name: "Nhân", gender: "male", meaning: "Nhân ái, con người" },
  { name: "Phát", gender: "male", meaning: "Phát triển, thịnh vượng" },
  { name: "Phong", gender: "male", meaning: "Phong cách, gió" },
  { name: "Phúc", gender: "male", meaning: "Phúc lành, may mắn" },
  { name: "Quân", gender: "male", meaning: "Quân tử, thanh lịch" },
  { name: "Quang", gender: "male", meaning: "Quang minh, sáng sủa" },
  { name: "Sơn", gender: "male", meaning: "Núi, vững chãi" },
  { name: "Tài", gender: "male", meaning: "Tài năng, giỏi giang" },
  { name: "Thành", gender: "male", meaning: "Thành công, thành đạt" },
  { name: "Thiện", gender: "male", meaning: "Thiện lành, tốt bụng" },
  { name: "Thịnh", gender: "male", meaning: "Thịnh vượng, phồn thịnh" },
  { name: "Trí", gender: "male", meaning: "Trí tuệ, thông minh" },
  { name: "Trung", gender: "male", meaning: "Trung thành, chính trực" },
  { name: "Tuấn", gender: "male", meaning: "Tuấn tú, tài giỏi" },
  { name: "Tùng", gender: "male", meaning: "Cây tùng, kiên cường" },
  { name: "Vĩ", gender: "male", meaning: "Vĩ đại, to lớn" },
  { name: "Vinh", gender: "male", meaning: "Vinh quang, vinh dự" },
  { name: "Vũ", gender: "male", meaning: "Vũ trụ, mưa" },
  { name: "Duy", gender: "male", meaning: "Duy nhất, đặc biệt" },
  { name: "Hưng", gender: "male", meaning: "Hưng thịnh, phát triển" },
  { name: "Khôi", gender: "male", meaning: "Khôi ngô, tuấn tú" },
  { name: "Lộc", gender: "male", meaning: "Phúc lộc, may mắn" },
  { name: "Quốc", gender: "male", meaning: "Quốc gia, đất nước" },
  { name: "Toàn", gender: "male", meaning: "Toàn vẹn, hoàn hảo" },
  { name: "Triết", gender: "male", meaning: "Triết lý, sâu sắc" },
  { name: "Thắng", gender: "male", meaning: "Chiến thắng, vượt trội" },
  { name: "Hào", gender: "male", meaning: "Hào hoa, phóng khoáng" },
  { name: "Đăng", gender: "male", meaning: "Đăng khoa, thành công" },

  // === Nữ ===
  { name: "Anh", gender: "unisex", meaning: "Anh hùng, xuất sắc" },
  { name: "Chi", gender: "female", meaning: "Chi lan, thanh nhã" },
  { name: "Diệp", gender: "female", meaning: "Lá cây, tươi mát" },
  { name: "Dung", gender: "female", meaning: "Dung nhan, xinh đẹp" },
  { name: "Giang", gender: "female", meaning: "Sông, bao la" },
  { name: "Hà", gender: "female", meaning: "Sông Hà, dịu dàng" },
  { name: "Hạnh", gender: "female", meaning: "Hạnh phúc, may mắn" },
  { name: "Hiền", gender: "female", meaning: "Hiền lành, dịu dàng" },
  { name: "Hoa", gender: "female", meaning: "Bông hoa, xinh đẹp" },
  { name: "Hương", gender: "female", meaning: "Hương thơm, ngọt ngào" },
  { name: "Khanh", gender: "female", meaning: "Khanh tướng, cao quý" },
  { name: "Lan", gender: "female", meaning: "Hoa lan, thanh cao" },
  { name: "Linh", gender: "unisex", meaning: "Linh thiêng, thông minh" },
  { name: "Loan", gender: "female", meaning: "Chim loan, quý phái" },
  { name: "Mai", gender: "female", meaning: "Hoa mai, thanh nhã" },
  { name: "My", gender: "female", meaning: "Xinh đẹp, mỹ miều" },
  { name: "Ngân", gender: "female", meaning: "Ngân hà, bạc" },
  { name: "Ngọc", gender: "female", meaning: "Ngọc quý, quý giá" },
  { name: "Nhung", gender: "female", meaning: "Nhung nhớ, mềm mại" },
  { name: "Phương", gender: "female", meaning: "Phương hướng, hương thơm" },
  { name: "Quỳnh", gender: "female", meaning: "Hoa quỳnh, xinh đẹp" },
  { name: "Thanh", gender: "unisex", meaning: "Thanh cao, trong sạch" },
  { name: "Thảo", gender: "female", meaning: "Cỏ cây, hiền thảo" },
  { name: "Thu", gender: "female", meaning: "Mùa thu, dịu dàng" },
  { name: "Thủy", gender: "female", meaning: "Nước, trong trẻo" },
  { name: "Trang", gender: "female", meaning: "Trang nhã, đẹp đẽ" },
  { name: "Trinh", gender: "female", meaning: "Trinh nguyên, trong sạch" },
  { name: "Trúc", gender: "female", meaning: "Cây trúc, thanh cao" },
  { name: "Tuyết", gender: "female", meaning: "Tuyết trắng, trong trẻo" },
  { name: "Uyên", gender: "female", meaning: "Uyên bác, học thức" },
  { name: "Vân", gender: "female", meaning: "Mây, tự do" },
  { name: "Vy", gender: "female", meaning: "Nhỏ nhắn, quý phái" },
  { name: "Yến", gender: "female", meaning: "Chim yến, duyên dáng" },
  { name: "Châu", gender: "female", meaning: "Châu ngọc, quý giá" },
  { name: "Đào", gender: "female", meaning: "Hoa đào, xinh đẹp" },
  { name: "Hằng", gender: "female", meaning: "Trăng, vĩnh hằng" },
  { name: "Huệ", gender: "female", meaning: "Hoa huệ, tinh khiết" },
  { name: "Khuê", gender: "female", meaning: "Sao khuê, tài năng" },
  { name: "Liên", gender: "female", meaning: "Hoa sen, thanh khiết" },
  { name: "Nhi", gender: "female", meaning: "Nhỏ bé, đáng yêu" },
  { name: "Thư", gender: "female", meaning: "Thư thái, nhẹ nhàng" },
  { name: "Trâm", gender: "female", meaning: "Trâm anh, cao quý" },
  { name: "Ánh", gender: "female", meaning: "Ánh sáng, rực rỡ" },
  { name: "Băng", gender: "female", meaning: "Băng giá, trong sáng" },
  { name: "Cúc", gender: "female", meaning: "Hoa cúc, kiên nhẫn" },
  { name: "Dao", gender: "female", meaning: "Tiên nữ, xinh đẹp" },
  { name: "Huyền", gender: "female", meaning: "Huyền bí, sâu sắc" },
  { name: "Kim", gender: "female", meaning: "Vàng, quý giá" },
  { name: "Nguyệt", gender: "female", meaning: "Trăng, dịu dàng" },
  { name: "Xuân", gender: "unisex", meaning: "Mùa xuân, tươi mới" },
];

// Tên đệm phổ biến
export const MIDDLE_NAMES: { name: string; gender: "male" | "female" | "unisex" }[] = [
  // Nam
  { name: "Văn", gender: "male" },
  { name: "Hữu", gender: "male" },
  { name: "Đức", gender: "male" },
  { name: "Công", gender: "male" },
  { name: "Quốc", gender: "male" },
  { name: "Minh", gender: "unisex" },
  { name: "Thanh", gender: "unisex" },
  { name: "Xuân", gender: "unisex" },
  // Nữ
  { name: "Thị", gender: "female" },
  { name: "Ngọc", gender: "female" },
  { name: "Thanh", gender: "unisex" },
  { name: "Phương", gender: "female" },
  { name: "Minh", gender: "unisex" },
  { name: "Thuỳ", gender: "female" },
  { name: "Hoài", gender: "female" },
  { name: "Gia", gender: "unisex" },
];

// Họ phổ biến ở Việt Nam
export const LAST_NAMES: string[] = [
  "Nguyễn", "Trần", "Lê", "Phạm", "Hoàng", "Huỳnh", "Phan", "Vũ",
  "Võ", "Đặng", "Bùi", "Đỗ", "Hồ", "Ngô", "Dương", "Lý",
  "Đào", "Đinh", "Lương", "Mai", "Trịnh", "Tô", "Cao", "Lâm",
];
