// ============================================================================
// Database tên tiếng Việt phổ biến cho bé
// ============================================================================

export interface VietnameseName {
  name: string;
  gender: "male" | "female" | "unisex";
  meaning: string;
}

export const VIETNAMESE_NAMES: VietnameseName[] = [
  // === Nam ===
  { name: "An", gender: "male", meaning: "Bình an, yên ổn" },
  { name: "Anh", gender: "unisex", meaning: "Anh hùng, xuất sắc" },
  { name: "Bảo", gender: "unisex", meaning: "Quý báu, bảo vệ" },
  { name: "Bình", gender: "male", meaning: "Bình yên, hòa bình" },
  { name: "Cường", gender: "male", meaning: "Mạnh mẽ, cường tráng" },
  { name: "Dũng", gender: "male", meaning: "Dũng cảm, can đảm" },
  { name: "Đạt", gender: "male", meaning: "Đạt được, thành đạt" },
  { name: "Đức", gender: "male", meaning: "Đức hạnh, phẩm chất tốt" },
  { name: "Hải", gender: "male", meaning: "Biển cả, rộng lớn" },
  { name: "Hiếu", gender: "male", meaning: "Hiếu thảo, có hiếu" },
  { name: "Hoàng", gender: "male", meaning: "Hoàng đế, vàng, cao quý" },
  { name: "Hùng", gender: "male", meaning: "Anh hùng, mạnh mẽ" },
  { name: "Huy", gender: "male", meaning: "Huy hoàng, rực rỡ" },
  { name: "Khải", gender: "male", meaning: "Khai sáng, mở ra" },
  { name: "Khang", gender: "male", meaning: "Khang trang, khỏe mạnh" },
  { name: "Khánh", gender: "unisex", meaning: "Khánh hỉ, vui mừng" },
  { name: "Kiên", gender: "male", meaning: "Kiên cường, bền bỉ" },
  { name: "Lâm", gender: "male", meaning: "Rừng, thiên nhiên" },
  { name: "Long", gender: "male", meaning: "Rồng, thịnh vượng" },
  { name: "Minh", gender: "unisex", meaning: "Sáng suốt, thông minh" },
  { name: "Nam", gender: "male", meaning: "Phương nam, nam tính" },
  { name: "Nghĩa", gender: "male", meaning: "Nghĩa khí, chính nghĩa" },
  { name: "Nhân", gender: "male", meaning: "Nhân ái, con người" },
  { name: "Phát", gender: "male", meaning: "Phát triển, thịnh vượng" },
  { name: "Phong", gender: "male", meaning: "Phong cách, gió" },
  { name: "Phúc", gender: "male", meaning: "Phúc lành, may mắn" },
  { name: "Quân", gender: "male", meaning: "Quân tử, thanh lịch" },
  { name: "Quang", gender: "male", meaning: "Quang minh, sáng sủa" },
  { name: "Sơn", gender: "male", meaning: "Núi, vững chãi" },
  { name: "Tài", gender: "male", meaning: "Tài năng, giỏi giang" },
  { name: "Thành", gender: "male", meaning: "Thành công, thành đạt" },
  { name: "Thiện", gender: "male", meaning: "Thiện lành, tốt bụng" },
  { name: "Thịnh", gender: "male", meaning: "Thịnh vượng, phồn thịnh" },
  { name: "Trí", gender: "male", meaning: "Trí tuệ, thông minh" },
  { name: "Trung", gender: "male", meaning: "Trung thành, chính trực" },
  { name: "Tuấn", gender: "male", meaning: "Tuấn tú, tài giỏi" },
  { name: "Tùng", gender: "male", meaning: "Cây tùng, kiên cường" },
  { name: "Vĩ", gender: "male", meaning: "Vĩ đại, to lớn" },
  { name: "Vinh", gender: "male", meaning: "Vinh quang, vinh dự" },
  { name: "Vũ", gender: "male", meaning: "Vũ trụ, mưa" },
  { name: "Duy", gender: "male", meaning: "Duy nhất, đặc biệt" },
  { name: "Hưng", gender: "male", meaning: "Hưng thịnh, phát triển" },
  { name: "Khôi", gender: "male", meaning: "Khôi ngô, tuấn tú" },
  { name: "Lộc", gender: "male", meaning: "Phúc lộc, may mắn" },
  { name: "Quốc", gender: "male", meaning: "Quốc gia, đất nước" },
  { name: "Toàn", gender: "male", meaning: "Toàn vẹn, hoàn hảo" },
  { name: "Triết", gender: "male", meaning: "Triết lý, sâu sắc" },
  { name: "Thắng", gender: "male", meaning: "Chiến thắng, vượt trội" },
  { name: "Hào", gender: "male", meaning: "Hào hoa, phóng khoáng" },
  { name: "Đăng", gender: "male", meaning: "Đăng khoa, thành công" },
  { name: "Công", gender: "male", meaning: "Công minh, công bằng" },
  { name: "Khoa", gender: "male", meaning: "Khoa bảng, tài năng" },
  { name: "Đông", gender: "male", meaning: "Phương đông, mùa đông" },
  { name: "Tâm", gender: "unisex", meaning: "Tấm lòng, trái tim" },
  { name: "Hậu", gender: "male", meaning: "Hậu thuẫn, phúc hậu" },
  { name: "Hiệp", gender: "male", meaning: "Hiệp sĩ, nghĩa hiệp" },
  { name: "Hòa", gender: "unisex", meaning: "Hòa bình, hòa hợp" },
  { name: "Lợi", gender: "male", meaning: "Lợi ích, thuận lợi" },
  { name: "Luân", gender: "male", meaning: "Luân lý, đạo đức" },
  { name: "Mạnh", gender: "male", meaning: "Mạnh mẽ, cường tráng" },
  { name: "Phi", gender: "male", meaning: "Bay cao, phi thường" },
  { name: "Sang", gender: "male", meaning: "Sang trọng, cao quý" },
  { name: "Sĩ", gender: "male", meaning: "Sĩ phu, học thức" },
  { name: "Tấn", gender: "male", meaning: "Tấn tới, tiến bộ" },
  { name: "Thái", gender: "male", meaning: "Thái bình, vĩ đại" },
  { name: "Thuận", gender: "male", meaning: "Thuận lợi, hòa thuận" },
  { name: "Tiến", gender: "male", meaning: "Tiến bộ, tiến lên" },
  { name: "Tín", gender: "male", meaning: "Tín nghĩa, đáng tin" },
  { name: "Trường", gender: "male", meaning: "Trường tồn, lâu dài" },
  { name: "Tuyến", gender: "male", meaning: "Tuyến đường, lựa chọn" },
  { name: "Uy", gender: "male", meaning: "Uy nghiêm, oai phong" },
  { name: "Việt", gender: "male", meaning: "Việt Nam, vượt qua" },
  { name: "Vương", gender: "male", meaning: "Vương giả, cao quý" },
  { name: "Dương", gender: "male", meaning: "Mặt trời, dương khí" },
  { name: "Định", gender: "male", meaning: "Định hướng, ổn định" },
  { name: "Chí", gender: "male", meaning: "Chí khí, ý chí" },
  { name: "Châu", gender: "male", meaning: "Châu ngọc, quý giá" },
  { name: "Dân", gender: "male", meaning: "Nhân dân, dân chủ" },
  { name: "Giang", gender: "male", meaning: "Sông lớn, bao la" },
  { name: "Kỳ", gender: "male", meaning: "Kỳ diệu, phi thường" },
  { name: "Lực", gender: "male", meaning: "Sức lực, mạnh mẽ" },
  { name: "Ninh", gender: "male", meaning: "Yên bình, an ninh" },
  { name: "Quý", gender: "male", meaning: "Quý giá, quý phái" },
  { name: "Sáng", gender: "male", meaning: "Sáng suốt, rạng rỡ" },
  { name: "Tháp", gender: "male", meaning: "Vững chãi, cao lớn" },
  { name: "Thọ", gender: "male", meaning: "Trường thọ, sống lâu" },
  { name: "Trực", gender: "male", meaning: "Chính trực, ngay thẳng" },
  { name: "Tuân", gender: "male", meaning: "Tuân thủ, kỷ luật" },
  { name: "Bách", gender: "male", meaning: "Cây bách, trăm — bền bỉ" },
  { name: "Đại", gender: "male", meaning: "To lớn, vĩ đại" },
  { name: "Hữu", gender: "male", meaning: "Có, hữu ích" },
  { name: "Nhật", gender: "male", meaning: "Mặt trời, Nhật Bản" },
  { name: "Phước", gender: "male", meaning: "Phước lành, may mắn" },
  // === Nam bổ sung ===
  { name: "Bằng", gender: "male", meaning: "Bằng hữu, công bằng" },
  { name: "Cảnh", gender: "male", meaning: "Cảnh sắc, đẹp đẽ" },
  { name: "Danh", gender: "male", meaning: "Danh tiếng, nổi tiếng" },
  { name: "Đoàn", gender: "male", meaning: "Đoàn kết, gắn bó" },
  { name: "Hà", gender: "male", meaning: "Sông, bao la rộng lớn" },
  { name: "Hạo", gender: "male", meaning: "Rộng lớn, bao la" },
  { name: "Khai", gender: "male", meaning: "Khai phá, mở đường" },
  { name: "Kiệt", gender: "male", meaning: "Kiệt xuất, tài giỏi" },
  { name: "Lương", gender: "male", meaning: "Lương thiện, tốt lành" },
  { name: "Nguyên", gender: "male", meaning: "Nguyên vẹn, thuần khiết" },
  { name: "Pháp", gender: "male", meaning: "Pháp luật, công chính" },
  { name: "Quảng", gender: "male", meaning: "Rộng rãi, bao dung" },
  { name: "Thông", gender: "male", meaning: "Thông minh, hiểu biết" },
  { name: "Trọng", gender: "male", meaning: "Trọng đại, quan trọng" },
  { name: "Vịnh", gender: "male", meaning: "Vịnh biển, bao la" },
  { name: "Xuân", gender: "male", meaning: "Mùa xuân, tươi mới" },
  { name: "Bách", gender: "male", meaning: "Cây bách, trường tồn" },
  { name: "Đan", gender: "male", meaning: "Son đỏ, chân thành" },
  { name: "Hùng Anh", gender: "male", meaning: "Anh hùng xuất sắc" },
  { name: "Khanh", gender: "male", meaning: "Khanh tướng, tài ba" },
  { name: "Lý", gender: "male", meaning: "Lý trí, sáng suốt" },
  { name: "Nhuận", gender: "male", meaning: "Nhuận sắc, đầy đủ" },
  { name: "Tấn Đạt", gender: "male", meaning: "Tiến bước thành đạt" },
  { name: "Thiên", gender: "male", meaning: "Trời, thiên phú" },
  { name: "Ân", gender: "male", meaning: "Ân nghĩa, biết ơn" },
  { name: "Bảng", gender: "male", meaning: "Bảng vàng, thành tích" },
  { name: "Đảo", gender: "male", meaning: "Hòn đảo, vững vàng" },
  { name: "Đỗ", gender: "male", meaning: "Đỗ đạt, thành công" },
  { name: "Hà Minh", gender: "male", meaning: "Sông sáng, minh triết" },
  { name: "Hoán", gender: "male", meaning: "Đổi mới, sáng tạo" },
  { name: "Khiêm", gender: "male", meaning: "Khiêm tốn, nhã nhặn" },
  { name: "Liêm", gender: "male", meaning: "Liêm chính, trong sạch" },
  { name: "Nghị", gender: "male", meaning: "Nghị lực, kiên cường" },
  { name: "Phú", gender: "male", meaning: "Giàu có, phú quý" },
  { name: "Quế", gender: "male", meaning: "Cây quế, quý giá" },
  { name: "Tân", gender: "male", meaning: "Mới mẻ, tươi mới" },
  { name: "Thế", gender: "male", meaning: "Thế giới, sức mạnh" },
  { name: "Trường Giang", gender: "male", meaning: "Sông dài, bền bỉ" },
  { name: "Uy Phong", gender: "male", meaning: "Uy nghiêm phong độ" },
  { name: "Bá", gender: "male", meaning: "Bá vương, thủ lĩnh" },
  { name: "Cang", gender: "male", meaning: "Cương trực, mạnh mẽ" },
  { name: "Đình", gender: "male", meaning: "Đình đám, nổi bật" },
  { name: "Hạnh", gender: "male", meaning: "Hạnh phúc, may mắn" },
  { name: "Khương", gender: "male", meaning: "Khương kiện, khỏe mạnh" },
  { name: "Lập", gender: "male", meaning: "Lập nghiệp, tự lập" },
  { name: "Minh Đức", gender: "male", meaning: "Sáng suốt đức hạnh" },
  { name: "Nhựt", gender: "male", meaning: "Mặt trời, rạng rỡ" },
  { name: "Quí", gender: "male", meaning: "Quý giá, quý trọng" },
  { name: "Tường", gender: "male", meaning: "Tường minh, rõ ràng" },
  { name: "Phương", gender: "male", meaning: "Phương hướng, đẹp đẽ" },
  { name: "Thạch", gender: "male", meaning: "Đá, vững chắc" },
  { name: "Triều", gender: "male", meaning: "Triều đại, thủy triều" },
  { name: "Vệ", gender: "male", meaning: "Bảo vệ, canh giữ" },
  { name: "Hùng Vĩ", gender: "male", meaning: "Hùng vĩ, to lớn" },
  { name: "Gia Bảo", gender: "male", meaning: "Báu vật của gia đình" },
  { name: "Gia Huy", gender: "male", meaning: "Huy hoàng gia đình" },
  { name: "Minh Quân", gender: "male", meaning: "Sáng suốt quân tử" },
  { name: "Nhật Minh", gender: "male", meaning: "Mặt trời sáng" },
  { name: "Quốc Anh", gender: "male", meaning: "Anh hùng đất nước" },
  { name: "Thiên Phúc", gender: "male", meaning: "Phúc trời ban" },
  { name: "Tuấn Kiệt", gender: "male", meaning: "Tuấn tú kiệt xuất" },
  { name: "Anh Khoa", gender: "male", meaning: "Khoa bảng anh tài" },
  { name: "Bảo Long", gender: "male", meaning: "Rồng quý, thịnh vượng" },
  { name: "Đăng Khoa", gender: "male", meaning: "Đỗ đạt khoa cử" },
  { name: "Hoàng Minh", gender: "male", meaning: "Vàng sáng, rạng ngời" },
  { name: "Quốc Huy", gender: "male", meaning: "Huy hoàng đất nước" },
  { name: "Thái Dương", gender: "male", meaning: "Mặt trời, rực rỡ" },
  { name: "Trí Dũng", gender: "male", meaning: "Trí tuệ dũng cảm" },
  { name: "Minh Triết", gender: "male", meaning: "Triết lý sáng suốt" },
  { name: "Hải Đăng", gender: "male", meaning: "Ngọn hải đăng, dẫn lối" },
  { name: "Anh Tuấn", gender: "male", meaning: "Anh tài tuấn tú" },
  { name: "Đức Trọng", gender: "male", meaning: "Đức hạnh trọng đại" },
  { name: "Quang Huy", gender: "male", meaning: "Quang minh huy hoàng" },
  // === Nữ ===
  { name: "Anh", gender: "unisex", meaning: "Anh hùng, xuất sắc" },
  { name: "Chi", gender: "female", meaning: "Chi lan, thanh nhã" },
  { name: "Diệp", gender: "female", meaning: "Lá cây, tươi mát" },
  { name: "Dung", gender: "female", meaning: "Dung nhan, xinh đẹp" },
  { name: "Giang", gender: "female", meaning: "Sông, bao la" },
  { name: "Hà", gender: "female", meaning: "Sông Hà, dịu dàng" },
  { name: "Hạnh", gender: "female", meaning: "Hạnh phúc, may mắn" },
  { name: "Hiền", gender: "female", meaning: "Hiền lành, dịu dàng" },
  { name: "Hoa", gender: "female", meaning: "Bông hoa, xinh đẹp" },
  { name: "Hương", gender: "female", meaning: "Hương thơm, ngọt ngào" },
  { name: "Khanh", gender: "female", meaning: "Khanh tướng, cao quý" },
  { name: "Lan", gender: "female", meaning: "Hoa lan, thanh cao" },
  { name: "Linh", gender: "unisex", meaning: "Linh thiêng, thông minh" },
  { name: "Loan", gender: "female", meaning: "Chim loan, quý phái" },
  { name: "Mai", gender: "female", meaning: "Hoa mai, thanh nhã" },
  { name: "My", gender: "female", meaning: "Xinh đẹp, mỹ miều" },
  { name: "Ngân", gender: "female", meaning: "Ngân hà, bạc" },
  { name: "Ngọc", gender: "female", meaning: "Ngọc quý, quý giá" },
  { name: "Nhung", gender: "female", meaning: "Nhung nhớ, mềm mại" },
  { name: "Phương", gender: "female", meaning: "Phương hướng, hương thơm" },
  { name: "Quỳnh", gender: "female", meaning: "Hoa quỳnh, xinh đẹp" },
  { name: "Thanh", gender: "unisex", meaning: "Thanh cao, trong sạch" },
  { name: "Thảo", gender: "female", meaning: "Cỏ cây, hiền thảo" },
  { name: "Thu", gender: "female", meaning: "Mùa thu, dịu dàng" },
  { name: "Thủy", gender: "female", meaning: "Nước, trong trẻo" },
  { name: "Trang", gender: "female", meaning: "Trang nhã, đẹp đẽ" },
  { name: "Trinh", gender: "female", meaning: "Trinh nguyên, trong sạch" },
  { name: "Trúc", gender: "female", meaning: "Cây trúc, thanh cao" },
  { name: "Tuyết", gender: "female", meaning: "Tuyết trắng, trong trẻo" },
  { name: "Uyên", gender: "female", meaning: "Uyên bác, học thức" },
  { name: "Vân", gender: "female", meaning: "Mây, tự do" },
  { name: "Vy", gender: "female", meaning: "Nhỏ nhắn, quý phái" },
  { name: "Yến", gender: "female", meaning: "Chim yến, duyên dáng" },
  { name: "Châu", gender: "female", meaning: "Châu ngọc, quý giá" },
  { name: "Đào", gender: "female", meaning: "Hoa đào, xinh đẹp" },
  { name: "Hằng", gender: "female", meaning: "Trăng, vĩnh hằng" },
  { name: "Huệ", gender: "female", meaning: "Hoa huệ, tinh khiết" },
  { name: "Khuê", gender: "female", meaning: "Sao khuê, tài năng" },
  { name: "Liên", gender: "female", meaning: "Hoa sen, thanh khiết" },
  { name: "Nhi", gender: "female", meaning: "Nhỏ bé, đáng yêu" },
  { name: "Thư", gender: "female", meaning: "Thư thái, nhẹ nhàng" },
  { name: "Trâm", gender: "female", meaning: "Trâm anh, cao quý" },
  { name: "Ánh", gender: "female", meaning: "Ánh sáng, rực rỡ" },
  { name: "Băng", gender: "female", meaning: "Băng giá, trong sáng" },
  { name: "Cúc", gender: "female", meaning: "Hoa cúc, kiên nhẫn" },
  { name: "Dao", gender: "female", meaning: "Tiên nữ, xinh đẹp" },
  { name: "Huyền", gender: "female", meaning: "Huyền bí, sâu sắc" },
  { name: "Kim", gender: "female", meaning: "Vàng, quý giá" },
  { name: "Nguyệt", gender: "female", meaning: "Trăng, dịu dàng" },
  { name: "Xuân", gender: "unisex", meaning: "Mùa xuân, tươi mới" },
  { name: "Bích", gender: "female", meaning: "Ngọc bích, quý giá" },
  { name: "Cẩm", gender: "female", meaning: "Cẩm thạch, đẹp đẽ" },
  { name: "Diễm", gender: "female", meaning: "Diễm lệ, xinh đẹp" },
  { name: "Đan", gender: "female", meaning: "Đan xen, khéo léo" },
  { name: "Hoài", gender: "female", meaning: "Hoài niệm, nhớ nhung" },
  { name: "Hồng", gender: "female", meaning: "Màu hồng, tươi đẹp" },
  { name: "Lệ", gender: "female", meaning: "Lệ hoa, xinh đẹp" },
  { name: "Mỹ", gender: "female", meaning: "Xinh đẹp, mỹ miều" },
  { name: "Như", gender: "female", meaning: "Như ý, toại nguyện" },
  { name: "Oanh", gender: "female", meaning: "Chim oanh, duyên dáng" },
  { name: "Thúy", gender: "female", meaning: "Thúy ngọc, xanh biếc" },
  { name: "Thùy", gender: "female", meaning: "Thùy mị, dịu dàng" },
  { name: "Tiên", gender: "female", meaning: "Tiên nữ, xinh đẹp" },
  { name: "Trà", gender: "female", meaning: "Trà hương, thanh nhã" },
  { name: "Yên", gender: "female", meaning: "Yên bình, tĩnh lặng" },
  { name: "Nga", gender: "female", meaning: "Hằng Nga, xinh đẹp" },
  { name: "Út", gender: "female", meaning: "Bé út, nhỏ nhất" },
  { name: "Quyên", gender: "female", meaning: "Quyên góp, đẹp đẽ" },
  { name: "Tuyền", gender: "female", meaning: "Suối nguồn, trong trẻo" },
  { name: "Thương", gender: "female", meaning: "Yêu thương, trìu mến" },
  { name: "Kiều", gender: "female", meaning: "Kiều diễm, xinh đẹp" },
  { name: "Lý", gender: "female", meaning: "Lý trí, thông minh" },
  { name: "Phượng", gender: "female", meaning: "Chim phượng, cao quý" },
  { name: "Tình", gender: "female", meaning: "Tình cảm, yêu thương" },
  { name: "Xuyến", gender: "female", meaning: "Xuyến chi, nhỏ xinh" },
  { name: "Diệu", gender: "female", meaning: "Diệu kỳ, tuyệt vời" },
  // === Nữ bổ sung ===
  { name: "An", gender: "female", meaning: "Bình an, yên ổn" },
  { name: "Bảo Châu", gender: "female", meaning: "Ngọc châu quý báu" },
  { name: "Bảo Trân", gender: "female", meaning: "Trân quý, quý giá" },
  { name: "Bích Ngọc", gender: "female", meaning: "Ngọc bích, quý phái" },
  { name: "Cẩm Tú", gender: "female", meaning: "Gấm đẹp, tinh xảo" },
  { name: "Diễm Quỳnh", gender: "female", meaning: "Đẹp như hoa quỳnh" },
  { name: "Đan Thanh", gender: "female", meaning: "Đan xen thanh nhã" },
  { name: "Gia Hân", gender: "female", meaning: "Niềm vui gia đình" },
  { name: "Hà My", gender: "female", meaning: "Sông đẹp, dịu dàng" },
  { name: "Hải Yến", gender: "female", meaning: "Chim yến biển" },
  { name: "Hoàng Yến", gender: "female", meaning: "Chim yến vàng" },
  { name: "Khánh Vy", gender: "female", meaning: "Vui mừng, quý phái" },
  { name: "Kim Ngân", gender: "female", meaning: "Vàng bạc, quý giá" },
  { name: "Lam", gender: "female", meaning: "Màu lam, bình yên" },
  { name: "Mẫn", gender: "female", meaning: "Mẫn tiệp, nhanh nhẹn" },
  { name: "Minh Châu", gender: "female", meaning: "Viên ngọc sáng" },
  { name: "Minh Thư", gender: "female", meaning: "Sáng suốt, thư thái" },
  { name: "Mộc", gender: "female", meaning: "Gỗ, giản dị thuần khiết" },
  { name: "Ngọc Anh", gender: "female", meaning: "Ngọc anh hoa" },
  { name: "Ngọc Hân", gender: "female", meaning: "Ngọc quý vui mừng" },
  { name: "Phương Anh", gender: "female", meaning: "Hương thơm anh hoa" },
  { name: "Phương Linh", gender: "female", meaning: "Hương linh thiêng" },
  { name: "Quỳnh Anh", gender: "female", meaning: "Hoa quỳnh anh hoa" },
  { name: "Song", gender: "female", meaning: "Đôi, hòa hợp" },
  { name: "Tâm Như", gender: "female", meaning: "Tấm lòng như ý" },
  { name: "Thanh Hà", gender: "female", meaning: "Sông trong, thanh nhã" },
  { name: "Thanh Trúc", gender: "female", meaning: "Trúc thanh cao" },
  { name: "Thảo Vy", gender: "female", meaning: "Hiền thảo quý phái" },
  { name: "Thiên Thanh", gender: "female", meaning: "Trời xanh, trong trẻo" },
  { name: "Thu Hà", gender: "female", meaning: "Sông mùa thu" },
  { name: "Thu Trang", gender: "female", meaning: "Mùa thu trang nhã" },
  { name: "Thuỳ Linh", gender: "female", meaning: "Dịu dàng linh thiêng" },
  { name: "Thuỳ Trang", gender: "female", meaning: "Thùy mị trang nhã" },
  { name: "Trà My", gender: "female", meaning: "Hoa trà đẹp" },
  { name: "Tường Vi", gender: "female", meaning: "Hoa tường vi" },
  { name: "Uyên Nhi", gender: "female", meaning: "Bé gái uyên bác" },
  { name: "Xuân Mai", gender: "female", meaning: "Hoa mai mùa xuân" },
  { name: "Yến Nhi", gender: "female", meaning: "Bé chim yến" },
  { name: "Bảo Ngọc", gender: "female", meaning: "Ngọc quý bảo vệ" },
  { name: "Hạ", gender: "female", meaning: "Mùa hè, tươi vui" },
  { name: "Khả Hân", gender: "female", meaning: "Đáng yêu, vui mừng" },
  { name: "Lam Phương", gender: "female", meaning: "Phương trời xanh" },
  { name: "Minh Anh", gender: "female", meaning: "Sáng suốt anh hoa" },
  { name: "Ngọc Diệp", gender: "female", meaning: "Lá ngọc, tươi mát" },
  { name: "Phương Vy", gender: "female", meaning: "Hương thơm quý phái" },
  { name: "Quỳnh Như", gender: "female", meaning: "Đẹp như hoa quỳnh" },
  { name: "Tuyết Mai", gender: "female", meaning: "Mai tuyết, kiên cường" },
  { name: "Uyển", gender: "female", meaning: "Uyển chuyển, duyên dáng" },
  { name: "Vương", gender: "female", meaning: "Vương giả, cao quý" },
  { name: "Đông", gender: "female", meaning: "Mùa đông, yên bình" },
  { name: "Hân", gender: "female", meaning: "Vui mừng, hạnh phúc" },
  { name: "Kha", gender: "female", meaning: "Hoa, đẹp đẽ" },
  { name: "Lệ Chi", gender: "female", meaning: "Cành lệ, thanh nhã" },
  { name: "Mộng", gender: "female", meaning: "Mộng mơ, lãng mạn" },
  { name: "Nhã", gender: "female", meaning: "Nhã nhặn, thanh lịch" },
  { name: "Phượng Linh", gender: "female", meaning: "Phượng hoàng linh thiêng" },
  { name: "Thiên Nga", gender: "female", meaning: "Thiên nga, thanh nhã" },
  { name: "Thuý An", gender: "female", meaning: "Xanh biếc bình an" },
  { name: "Trúc Mai", gender: "female", meaning: "Trúc mai, bạn tri kỷ" },
  { name: "Hà Phương", gender: "female", meaning: "Phương trời sông" },
  { name: "Ngọc Trâm", gender: "female", meaning: "Trâm ngọc, cao quý" },
  { name: "Thanh Ngân", gender: "female", meaning: "Ngân thanh, trong trẻo" },
  { name: "Xuân Nhi", gender: "female", meaning: "Bé mùa xuân" },
  { name: "Ánh Dương", gender: "female", meaning: "Ánh mặt trời" },
  { name: "Hoàng Anh", gender: "female", meaning: "Chim hoàng anh, rực rỡ" },
  { name: "Khánh Ngọc", gender: "female", meaning: "Ngọc mừng, quý giá" },
  { name: "Phương Thảo", gender: "female", meaning: "Cỏ thơm, hiền thảo" },
];

// ============================================================================
// Tên gợi ý 2026 — 100 tên hiện đại, phổ biến (50 nam + 50 nữ)
// Dùng cho engine gợi ý. VIETNAMESE_NAMES ở trên giữ cho filter tên kiêng.
// ============================================================================
export const SUGGEST_NAMES: VietnameseName[] = [
  // ===================== NAM (50) =====================
  // --- Tên đơn phổ biến ---
  { name: "An", gender: "male", meaning: "Bình an, yên ổn" },
  { name: "Bảo", gender: "male", meaning: "Quý báu, bảo vệ" },
  { name: "Đức", gender: "male", meaning: "Đức hạnh, phẩm chất tốt" },
  { name: "Huy", gender: "male", meaning: "Huy hoàng, rực rỡ" },
  { name: "Khang", gender: "male", meaning: "Khỏe mạnh, vững vàng" },
  { name: "Khôi", gender: "male", meaning: "Khôi ngô, tuấn tú" },
  { name: "Kiên", gender: "male", meaning: "Kiên cường, bền bỉ" },
  { name: "Lâm", gender: "male", meaning: "Rừng, thiên nhiên xanh mát" },
  { name: "Long", gender: "male", meaning: "Rồng, thịnh vượng" },
  { name: "Minh", gender: "male", meaning: "Sáng suốt, thông minh" },
  { name: "Phúc", gender: "male", meaning: "Phúc lành, may mắn" },
  { name: "Quân", gender: "male", meaning: "Quân tử, thanh lịch" },
  { name: "Thịnh", gender: "male", meaning: "Thịnh vượng, phồn thịnh" },
  { name: "Trí", gender: "male", meaning: "Trí tuệ, thông minh" },
  { name: "Tuấn", gender: "male", meaning: "Tuấn tú, tài giỏi" },
  { name: "Dũng", gender: "male", meaning: "Dũng cảm, can đảm" },
  { name: "Phong", gender: "male", meaning: "Phong cách, phong độ" },
  { name: "Khải", gender: "male", meaning: "Khai sáng, mở đường" },
  { name: "Thiện", gender: "male", meaning: "Thiện lành, tốt bụng" },
  { name: "Nghĩa", gender: "male", meaning: "Nghĩa khí, chính nghĩa" },
  // --- Tên ghép hiện đại ---
  { name: "Gia Bảo", gender: "male", meaning: "Báu vật của gia đình" },
  { name: "Gia Huy", gender: "male", meaning: "Huy hoàng gia đình" },
  { name: "Minh Khang", gender: "male", meaning: "Sáng suốt, khỏe mạnh" },
  { name: "Đăng Khoa", gender: "male", meaning: "Đỗ đạt khoa cử" },
  { name: "Nhật Minh", gender: "male", meaning: "Mặt trời sáng rạng" },
  { name: "Tuệ Minh", gender: "male", meaning: "Trí tuệ sáng suốt" },
  { name: "Anh Khoa", gender: "male", meaning: "Khoa bảng anh tài" },
  { name: "Bảo Long", gender: "male", meaning: "Rồng quý, thịnh vượng" },
  { name: "Đức Minh", gender: "male", meaning: "Đạo đức sáng suốt" },
  { name: "Hoàng Minh", gender: "male", meaning: "Vàng sáng, rạng ngời" },
  { name: "Thiên Phúc", gender: "male", meaning: "Phúc trời ban" },
  { name: "Minh Triết", gender: "male", meaning: "Triết lý sáng suốt" },
  { name: "Hải Đăng", gender: "male", meaning: "Ngọn hải đăng dẫn lối" },
  { name: "Quang Huy", gender: "male", meaning: "Quang minh huy hoàng" },
  { name: "An Phúc", gender: "male", meaning: "Bình an phúc lành" },
  { name: "Thiện Long", gender: "male", meaning: "Rồng hiền, nội lực mạnh" },
  { name: "Đức Thịnh", gender: "male", meaning: "Đức hạnh thịnh vượng" },
  { name: "Trí Dũng", gender: "male", meaning: "Trí tuệ dũng cảm" },
  { name: "Thiện Nhân", gender: "male", meaning: "Người nhân hậu" },
  { name: "Minh Quân", gender: "male", meaning: "Sáng suốt quân tử" },
  { name: "Anh Tuấn", gender: "male", meaning: "Anh tài tuấn tú" },
  { name: "Bảo Dũng", gender: "male", meaning: "Bảo vệ sự can đảm" },
  { name: "Gia Khang", gender: "male", meaning: "Gia đình khỏe mạnh" },
  { name: "Quốc Huy", gender: "male", meaning: "Huy hoàng đất nước" },
  { name: "Đức Trọng", gender: "male", meaning: "Đức hạnh trọng đại" },
  { name: "Thái Dương", gender: "male", meaning: "Mặt trời rực rỡ" },
  { name: "Sơn Hải", gender: "male", meaning: "Núi biển, tầm vóc lớn" },
  { name: "Khánh Vinh", gender: "male", meaning: "Vinh quang và niềm vui" },
  { name: "Bảo Đức", gender: "male", meaning: "Giữ gìn phẩm hạnh" },
  { name: "Tuấn Kiệt", gender: "male", meaning: "Tuấn tú kiệt xuất" },

  // ===================== NỮ (50) =====================
  // --- Tên đơn phổ biến ---
  { name: "An", gender: "female", meaning: "Bình an, yên ổn" },
  { name: "Hân", gender: "female", meaning: "Vui mừng, hạnh phúc" },
  { name: "Linh", gender: "female", meaning: "Linh thiêng, thông minh" },
  { name: "Mai", gender: "female", meaning: "Hoa mai, thanh nhã" },
  { name: "Ngọc", gender: "female", meaning: "Ngọc quý, quý giá" },
  { name: "Thư", gender: "female", meaning: "Thư thái, nhẹ nhàng" },
  { name: "Vy", gender: "female", meaning: "Nhỏ nhắn, quý phái" },
  { name: "Quỳnh", gender: "female", meaning: "Hoa quỳnh, xinh đẹp" },
  { name: "Trúc", gender: "female", meaning: "Cây trúc, thanh cao" },
  { name: "Khuê", gender: "female", meaning: "Sao Khuê, tài năng" },
  { name: "Diệu", gender: "female", meaning: "Diệu kỳ, tuyệt vời" },
  { name: "Nhã", gender: "female", meaning: "Nhã nhặn, thanh lịch" },
  { name: "Trang", gender: "female", meaning: "Trang nhã, đẹp đẽ" },
  { name: "Hiền", gender: "female", meaning: "Hiền lành, dịu dàng" },
  { name: "Thảo", gender: "female", meaning: "Hiền thảo, cỏ cây" },
  { name: "Uyên", gender: "female", meaning: "Uyên bác, học thức" },
  { name: "Nhi", gender: "female", meaning: "Nhỏ bé, đáng yêu" },
  { name: "Hương", gender: "female", meaning: "Hương thơm, ngọt ngào" },
  { name: "Lan", gender: "female", meaning: "Hoa lan, thanh cao" },
  { name: "Châu", gender: "female", meaning: "Châu ngọc, quý giá" },
  // --- Tên ghép hiện đại ---
  { name: "An Nhiên", gender: "female", meaning: "Bình an, tự nhiên" },
  { name: "Gia Hân", gender: "female", meaning: "Niềm vui gia đình" },
  { name: "Khánh Vy", gender: "female", meaning: "Vui mừng, quý phái" },
  { name: "Minh Anh", gender: "female", meaning: "Sáng suốt anh hoa" },
  { name: "Bảo Ngọc", gender: "female", meaning: "Ngọc quý bảo vệ" },
  { name: "Phương Anh", gender: "female", meaning: "Hương thơm anh hoa" },
  { name: "Thảo Vy", gender: "female", meaning: "Hiền thảo quý phái" },
  { name: "Ngọc Hân", gender: "female", meaning: "Ngọc quý vui mừng" },
  { name: "Quỳnh Anh", gender: "female", meaning: "Hoa quỳnh anh hoa" },
  { name: "Minh Thư", gender: "female", meaning: "Sáng suốt, thư thái" },
  { name: "Thanh Trúc", gender: "female", meaning: "Trúc thanh cao" },
  { name: "Thu Trang", gender: "female", meaning: "Mùa thu trang nhã" },
  { name: "Diễm Quỳnh", gender: "female", meaning: "Đẹp kiều diễm như hoa" },
  { name: "Minh Khuê", gender: "female", meaning: "Sáng như sao Khuê" },
  { name: "Khả Hân", gender: "female", meaning: "Đáng yêu, vui mừng" },
  { name: "Tường Vi", gender: "female", meaning: "Hoa tường vi, duyên dáng" },
  { name: "Khánh An", gender: "female", meaning: "Niềm vui bình an" },
  { name: "Anh Thư", gender: "female", meaning: "Thông minh, bản lĩnh" },
  { name: "Trà My", gender: "female", meaning: "Hoa trà đẹp" },
  { name: "Phương Linh", gender: "female", meaning: "Hương linh thiêng" },
  { name: "Cát Tường", gender: "female", meaning: "May mắn, tốt lành" },
  { name: "Thiên Thanh", gender: "female", meaning: "Trời xanh, trong trẻo" },
  { name: "Ánh Dương", gender: "female", meaning: "Ánh mặt trời rạng rỡ" },
  { name: "Bảo Trân", gender: "female", meaning: "Trân quý, quý giá" },
  { name: "Thuỳ Linh", gender: "female", meaning: "Dịu dàng linh thiêng" },
  { name: "Xuân Mai", gender: "female", meaning: "Hoa mai mùa xuân" },
  { name: "Hà My", gender: "female", meaning: "Dòng sông đẹp" },
  { name: "Thanh Hà", gender: "female", meaning: "Dòng sông trong, thanh nhã" },
  { name: "Mai Phương", gender: "female", meaning: "Hoa mai phương xa" },
  { name: "Tuệ Lâm", gender: "female", meaning: "Trí tuệ sâu rộng" },
];

// Tên đệm phổ biến
export const MIDDLE_NAMES: { name: string; gender: "male" | "female" }[] = [
  // === Nam ===
  { name: "Văn", gender: "male" },
  { name: "Hữu", gender: "male" },
  { name: "Đức", gender: "male" },
  { name: "Công", gender: "male" },
  { name: "Quốc", gender: "male" },
  { name: "Minh", gender: "male" },
  { name: "Thanh", gender: "male" },
  { name: "Xuân", gender: "male" },
  { name: "Gia", gender: "male" },
  { name: "Anh", gender: "male" },
  { name: "Bảo", gender: "male" },
  { name: "Trọng", gender: "male" },
  { name: "Tiến", gender: "male" },
  { name: "Đình", gender: "male" },
  { name: "Nhật", gender: "male" },
  { name: "Trung", gender: "male" },
  { name: "Thành", gender: "male" },
  { name: "Đại", gender: "male" },
  { name: "Hoàng", gender: "male" },
  { name: "Phúc", gender: "male" },
  // === Nữ ===
  { name: "Thị", gender: "female" },
  { name: "Ngọc", gender: "female" },
  { name: "Phương", gender: "female" },
  { name: "Thuỳ", gender: "female" },
  { name: "Hoài", gender: "female" },
  { name: "Thanh", gender: "female" },
  { name: "Minh", gender: "female" },
  { name: "Xuân", gender: "female" },
  { name: "Bích", gender: "female" },
  { name: "Diệu", gender: "female" },
  { name: "Hồng", gender: "female" },
  { name: "Kim", gender: "female" },
  { name: "Mỹ", gender: "female" },
  { name: "Tường", gender: "female" },
  { name: "Yên", gender: "female" },
  { name: "Gia", gender: "female" },
  { name: "Hải", gender: "female" },
  { name: "Khánh", gender: "female" },
  { name: "Thiên", gender: "female" },
  { name: "Quỳnh", gender: "female" },
];

// Họ phổ biến ở Việt Nam
export const LAST_NAMES: string[] = [
  "Nguyễn", "Trần", "Lê", "Phạm", "Hoàng", "Huỳnh", "Phan", "Vũ",
  "Võ", "Đặng", "Bùi", "Đỗ", "Hồ", "Ngô", "Dương", "Lý",
  "Đào", "Đinh", "Lương", "Mai", "Trịnh", "Tô", "Cao", "Lâm",
];

// Biệt danh phổ biến cho bé
export interface Nickname {
  name: string;
  gender: "male" | "female" | "unisex";
  category: "cute" | "animal" | "fruit" | "nature" | "english" | "other";
  meaning: string;
}

export const NICKNAMES: Nickname[] = [
  // === Dễ thương ===
  { name: "Bông", gender: "unisex", category: "cute", meaning: "Bông hoa, mềm mại" },
  { name: "Bin", gender: "male", category: "cute", meaning: "Bé nhỏ, đáng yêu" },
  { name: "Bí", gender: "unisex", category: "cute", meaning: "Bí ẩn, dễ thương" },
  { name: "Bi", gender: "unisex", category: "cute", meaning: "Viên bi, tròn xinh" },
  { name: "Bo", gender: "male", category: "cute", meaning: "Bé Bo, vui vẻ" },
  { name: "Bún", gender: "female", category: "cute", meaning: "Mềm mại, trắng trẻo" },
  { name: "Búp", gender: "female", category: "cute", meaning: "Búp bê, xinh xắn" },
  { name: "Na", gender: "female", category: "cute", meaning: "Bé Na, ngọt ngào" },
  { name: "Nấm", gender: "female", category: "cute", meaning: "Nấm nhỏ, đáng yêu" },
  { name: "Su", gender: "female", category: "cute", meaning: "Bé Su, dịu dàng" },
  { name: "Sóc", gender: "unisex", category: "cute", meaning: "Nhanh nhẹn, hoạt bát" },
  { name: "Tí", gender: "unisex", category: "cute", meaning: "Bé tí, nhỏ nhắn" },
  { name: "Tép", gender: "female", category: "cute", meaning: "Tép nhỏ, xinh xắn" },
  { name: "Bầu", gender: "unisex", category: "cute", meaning: "Tròn tròn, dễ thương" },
  { name: "Cún", gender: "male", category: "cute", meaning: "Cún con, nghịch ngợm" },
  { name: "Mập", gender: "unisex", category: "cute", meaning: "Bụ bẫm, khỏe mạnh" },
  { name: "Sữa", gender: "unisex", category: "cute", meaning: "Trắng trẻo, ngọt ngào" },
  { name: "Nhím", gender: "unisex", category: "cute", meaning: "Nhỏ nhắn, đáng yêu" },
  { name: "Bơ", gender: "unisex", category: "cute", meaning: "Mịn màng, dễ thương" },
  { name: "Gạo", gender: "unisex", category: "cute", meaning: "Thuần khiết, giản dị" },

  // === Động vật ===
  { name: "Gấu", gender: "male", category: "animal", meaning: "Mạnh mẽ, ấm áp" },
  { name: "Mèo", gender: "female", category: "animal", meaning: "Khéo léo, duyên dáng" },
  { name: "Cáo", gender: "male", category: "animal", meaning: "Thông minh, nhanh nhẹn" },
  { name: "Thỏ", gender: "female", category: "animal", meaning: "Hiền lành, dễ thương" },
  { name: "Cọp", gender: "male", category: "animal", meaning: "Dũng mãnh, mạnh mẽ" },
  { name: "Ong", gender: "unisex", category: "animal", meaning: "Chăm chỉ, siêng năng" },
  { name: "Voi", gender: "male", category: "animal", meaning: "To lớn, hiền lành" },
  { name: "Kiến", gender: "unisex", category: "animal", meaning: "Kiên trì, đoàn kết" },
  { name: "Sáo", gender: "female", category: "animal", meaning: "Vui tươi, ca hát" },
  { name: "Rồng", gender: "male", category: "animal", meaning: "Quyền lực, cao quý" },

  // === Trái cây ===
  { name: "Táo", gender: "unisex", category: "fruit", meaning: "Tươi mát, khỏe mạnh" },
  { name: "Đào", gender: "female", category: "fruit", meaning: "Hồng hào, xinh đẹp" },
  { name: "Cam", gender: "unisex", category: "fruit", meaning: "Ngọt ngào, tươi sáng" },
  { name: "Xoài", gender: "unisex", category: "fruit", meaning: "Ngọt ngào, nhiệt đới" },
  { name: "Mít", gender: "male", category: "fruit", meaning: "Ngọt lịm, vui vẻ" },
  { name: "Dâu", gender: "female", category: "fruit", meaning: "Nhỏ xinh, ngọt ngào" },
  { name: "Cherry", gender: "female", category: "fruit", meaning: "Ngọt ngào, đáng yêu" },
  { name: "Nho", gender: "unisex", category: "fruit", meaning: "Nhỏ nhắn, quý giá" },
  { name: "Chanh", gender: "unisex", category: "fruit", meaning: "Tươi mát, sảng khoái" },
  { name: "Lựu", gender: "female", category: "fruit", meaning: "Đỏ thắm, may mắn" },

  // === Thiên nhiên ===
  { name: "Mây", gender: "female", category: "nature", meaning: "Nhẹ nhàng, tự do" },
  { name: "Sao", gender: "female", category: "nature", meaning: "Lấp lánh, rực rỡ" },
  { name: "Nắng", gender: "female", category: "nature", meaning: "Ấm áp, tươi sáng" },
  { name: "Gió", gender: "male", category: "nature", meaning: "Tự do, phóng khoáng" },
  { name: "Suối", gender: "female", category: "nature", meaning: "Trong trẻo, êm đềm" },
  { name: "Sương", gender: "female", category: "nature", meaning: "Mát lành, thanh khiết" },
  { name: "Lá", gender: "unisex", category: "nature", meaning: "Tươi xanh, sinh động" },
  { name: "Sen", gender: "female", category: "nature", meaning: "Thanh khiết, cao quý" },

  // === Tên tiếng Anh / quốc tế ===
  { name: "Lucky", gender: "unisex", category: "english", meaning: "May mắn" },
  { name: "Sunny", gender: "unisex", category: "english", meaning: "Rạng rỡ, vui vẻ" },
  { name: "Ben", gender: "male", category: "english", meaning: "Con trai, phước lành" },
  { name: "Tom", gender: "male", category: "english", meaning: "Cậu bé, giản dị" },
  { name: "Mia", gender: "female", category: "english", meaning: "Của tôi, yêu thương" },
  { name: "Lily", gender: "female", category: "english", meaning: "Hoa lily, tinh khiết" },
  { name: "Amy", gender: "female", category: "english", meaning: "Yêu dấu" },
  { name: "Sam", gender: "male", category: "english", meaning: "Được lắng nghe" },
  { name: "Max", gender: "male", category: "english", meaning: "Vĩ đại nhất" },
  { name: "Luna", gender: "female", category: "english", meaning: "Mặt trăng" },

  // === Trending 2026 — Năm Bính Ngọ (Ngựa Lửa) ===
  { name: "Ngựa", gender: "male", category: "animal", meaning: "Mạnh mẽ, tự do — con giáp 2026" },
  { name: "Pony", gender: "unisex", category: "english", meaning: "Ngựa nhỏ, năng động" },
  { name: "Lửa", gender: "male", category: "nature", meaning: "Nhiệt huyết, bùng cháy — Bính Ngọ" },
  { name: "Cỏ", gender: "unisex", category: "nature", meaning: "Giản dị, sức sống mãnh liệt" },
  { name: "Mây Bay", gender: "female", category: "nature", meaning: "Tự do, phiêu lưu" },
  { name: "Hổ Phách", gender: "unisex", category: "nature", meaning: "Ấm áp, quý giá — tông lửa" },

  // === Gen Alpha / TikTok trending ===
  { name: "Boba", gender: "unisex", category: "other", meaning: "Trà sữa, ngọt ngào trendy" },
  { name: "Latte", gender: "unisex", category: "other", meaning: "Mịn màng, thanh lịch" },
  { name: "Matcha", gender: "unisex", category: "other", meaning: "Tươi mát, healthy" },
  { name: "Oreo", gender: "unisex", category: "other", meaning: "Đen trắng, vui nhộn" },
  { name: "Donut", gender: "unisex", category: "other", meaning: "Tròn xinh, ngọt ngào" },
  { name: "Jellybean", gender: "unisex", category: "other", meaning: "Nhiều màu sắc, vui vẻ" },
  { name: "Cookie", gender: "unisex", category: "other", meaning: "Ngọt ngào, ai cũng yêu" },
  { name: "Marshmallow", gender: "unisex", category: "other", meaning: "Mềm mịn, trắng trẻo" },

  // === Tên Hàn / Nhật trending ===
  { name: "Yuki", gender: "female", category: "english", meaning: "Tuyết (Nhật), tinh khiết" },
  { name: "Haru", gender: "unisex", category: "english", meaning: "Mùa xuân (Nhật), tươi mới" },
  { name: "Momo", gender: "female", category: "english", meaning: "Đào (Nhật), xinh đẹp" },
  { name: "Sora", gender: "unisex", category: "english", meaning: "Bầu trời (Nhật), tự do" },
  { name: "Kimi", gender: "female", category: "english", meaning: "Người quý giá (Nhật)" },
  { name: "Ryu", gender: "male", category: "english", meaning: "Rồng (Nhật), mạnh mẽ" },
  { name: "Kai", gender: "male", category: "english", meaning: "Biển (Nhật/Hawaii), rộng lớn" },

  // === Dễ thương bổ sung ===
  { name: "Kẹo", gender: "female", category: "cute", meaning: "Ngọt ngào, rực rỡ" },
  { name: "Sún", gender: "unisex", category: "cute", meaning: "Bé sún, đáng yêu" },
  { name: "Tôm", gender: "male", category: "cute", meaning: "Bé Tôm, nghịch ngợm" },
  { name: "Cà", gender: "unisex", category: "cute", meaning: "Bé Cà, giản dị" },
  { name: "Mũm", gender: "unisex", category: "cute", meaning: "Mũm mĩm, bụ bẫm" },
  { name: "Bắp", gender: "male", category: "cute", meaning: "Bắp ngô, khỏe mạnh" },
  { name: "Đậu", gender: "unisex", category: "cute", meaning: "Đậu nhỏ, xinh xắn" },
  { name: "Mèo Con", gender: "female", category: "cute", meaning: "Nhỏ nhắn, duyên dáng" },
  { name: "Gấu Bông", gender: "unisex", category: "cute", meaning: "Ôm ấp, dễ thương" },

  // === Khác ===
  { name: "Ku", gender: "male", category: "other", meaning: "Bé trai, dễ thương" },
  { name: "Mimi", gender: "female", category: "other", meaning: "Nhỏ nhắn, xinh xắn" },
  { name: "Bon", gender: "male", category: "other", meaning: "Tốt lành, vui vẻ" },
  { name: "Tin", gender: "male", category: "other", meaning: "Niềm tin, hy vọng" },
  { name: "Min", gender: "unisex", category: "other", meaning: "Nhỏ bé, thông minh" },
  { name: "Kiwi", gender: "unisex", category: "other", meaning: "Độc đáo, tươi mới" },
  { name: "Mochi", gender: "unisex", category: "other", meaning: "Mềm mại, ngọt ngào" },
  { name: "Pudding", gender: "unisex", category: "other", meaning: "Ngọt ngào, mềm mịn" },
  { name: "Chip", gender: "male", category: "other", meaning: "Nhỏ gọn, nhanh nhẹn" },
  { name: "Nana", gender: "female", category: "other", meaning: "Duyên dáng, dễ thương" },
];
